server:
  port: 9000
spring:
  config:
    import: "optional:configserver:http://localhost:9003"
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      mvc:
        routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
        - id: DEPARTMENT-SERVICE
          uri: lb://DEPARTMENT-SERVICE
          predicates:
            - Path=/departments/**
    