server:
  port: 9003
  
spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/NamPhan123/config-server
          clone-on-start: true  
    
